/* Generated By:JJTree: Do not edit this line. ASTArrowType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrowType extends SimpleNode implements Type {
  public ASTArrowType(int id) {
    super(id);
  }

  public ASTArrowType(Parser p, int id) {
    super(p, id);
  }
  
  /* MY CUSTOMIZATION OF ASTArrowType */
  public Type getLeft() {return (Type) jjtGetChild(0);}
  public Type getRight() {return (Type) jjtGetChild(1);}
  
  public boolean equals(Object obj){
	  if (obj instanceof ASTArrowType) {
		  return getLeft().equals(((ASTArrowType) obj).getLeft()) && getRight().equals(((ASTArrowType) obj).getRight());
	  }
	  else return false;
  }
  
  public Type type() {
	  ASTType arrow=new ASTType(ParserTreeConstants.JJTTYPE);
	  arrow.jjtSetValue("Arrow");
	  return arrow;
  }
  
  
  
  
}
/* JavaCC - OriginalChecksum=15c0140043f3331072494743824302ed (do not edit this line) */
