/* Generated By:JJTree: Do not edit this line. ASTApp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTApp extends SimpleNode implements Type {
  public ASTApp(int id) {
    super(id);
  }

  public ASTApp(Parser p, int id) {
    super(p, id);
  }
  
  /* MY CUSTOMIZATION OF ASTApp */
  
  public Node getLeft() {return jjtGetChild(0);}
  public Node getRight() {return jjtGetChild(1);}
  
  public Type type() throws TypeException {
	  Type lefttype=getLeft().type();
	  Type righttype=getRight().type();
	  //These may raise a TypeException if left and right parts are not well-typed.
	  if (!(lefttype instanceof ASTArrowType)) 
	  {throw new TypeException("Left part of an Application must be of Arrow Type");}
	  Type exptype=((ASTArrowType) lefttype).getLeft();
	  Type rettype=((ASTArrowType) lefttype).getRight();
	  if (!(exptype.equals(righttype))) 
	  {throw new TypeException("The argument passed to the function is not of the expected type.");}
	  return rettype;
  }

}
/* JavaCC - OriginalChecksum=fcb9d06c6b47c87037ea56fdfda8a927 (do not edit this line) */
