import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/* Generated By:JJTree: Do not edit this line. ASTBool.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBool extends SimpleNode implements Type {
  public ASTBool(int id) {
    super(id);
  }

  public ASTBool(Parser p, int id) {
    super(p, id);
  }
  
  public Node getNom() { return (Node)jjtGetChild(1);}
  
  public Type type() {
	  ASTType booltype=new ASTType(ParserTreeConstants.JJTTYPE);
	  booltype.jjtSetValue("Bool");
	  return booltype;
  }
  
  public boolean equals(Object o) {
	  if(o instanceof ASTBool)
		  return true;
	  return false;
  }
  
  public List<OOTStatement> code() throws TypeException {
	  List<OOTStatement> listeRes = new ArrayList<OOTStatement>();
	  OOTConstant<OOTTypeBool> c = new OOTConstant<OOTTypeBool>(new OOTTypeBool(),String.valueOf(this.jjtGetValue()));
	  listeRes.add(c);
	  Iterator<OOTStatement> it = listeRes.iterator();
	  while(it.hasNext())
		  System.out.println(it.next().genCodeState("Toto.java"));//???????????????????
	  return listeRes;
  }

 
}
/* JavaCC - OriginalChecksum=5338006369a499dda77b186afc8e45e3 (do not edit this line) */
