import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/* Generated By:JJTree: Do not edit this line. ASTInt.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInt extends SimpleNode implements Type {
  public ASTInt(int id) {
    super(id);
  }

  public ASTInt(Parser p, int id) {
    super(p, id);
  }
  
  /* MY CUSTOMIZATION OF ASTInt */
  
  public Type type() {
	  ASTType inttype=new ASTType(ParserTreeConstants.JJTTYPE);
	  inttype.jjtSetValue("Int");
	  return inttype;
  }

  public boolean equals(Object o) {
	  if(o instanceof ASTInt)
		  return true;
	  return false;
  }
  
  public List<OOTStatement> code() throws TypeException {
	  List<OOTStatement> listeRes = new ArrayList<OOTStatement>();
	  OOTConstant<OOTTypeInt> c = new OOTConstant<OOTTypeInt>(new OOTTypeInt(),String.valueOf(this.jjtGetValue()));
	  listeRes.add(c);
	  Iterator<OOTStatement> it = listeRes.iterator();
	  while(it.hasNext())
		  System.out.println(it.next().genCodeState("Toto.java"));
	  return listeRes;
  }

}
/* JavaCC - OriginalChecksum=6a8423e99857155e35c68311457c4303 (do not edit this line) */
