/* Generated By:JJTree: Do not edit this line. ASTNull.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNull extends SimpleNode {
  public ASTNull(int id) {
    super(id);
  }

  public ASTNull(Parser p, int id) {
    super(p, id);
  }
  
  public Type type() {
	  ASTType nulltype=new ASTType(ParserTreeConstants.JJTTYPE);
	  nulltype.jjtSetValue("Null");
	  return nulltype;
  }
  
  public boolean equals(Object o) {
	  if(o instanceof ASTNull)
		  return true;
	  return false;
  }

}
/* JavaCC - OriginalChecksum=356a4aec16669d1205e9a1b3bb4e432b (do not edit this line) */
