import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/* Generated By:JJTree: Do not edit this line. ASTOpp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOpp extends SimpleNode implements Type {
 
	public ASTOpp(int id) {
    super(id);
  }

  
	public ASTOpp(Parser p, int id) {
    super(p, id);
  }
  
	public Node getLeft() { return (Node)jjtGetChild(0);}
  
	public Type type() throws TypeException {
	  Node left = (Node)jjtGetChild(0);
	  ASTInt inttype = new ASTInt(ParserTreeConstants.JJTTYPE);
	  if(!left.type().equals(inttype.type()))
		  throw new TypeException("Oh! This is not an Integer");
	  return left.type();	  
  }

	public List<OOTStatement> code() throws TypeException {
		OOTNode left=null;
		OOTOper opp=null;
		List<OOTStatement> ls = new ArrayList<OOTStatement>();
		int i=0;
		if(this.getLeft() instanceof ASTTermVar) {
			ASTTermVar l = (ASTTermVar)this.getLeft();
			left = new OOTVar<OOTTypeInt>("public",l.getName(),new OOTTypeInt());
		} else if(this.getLeft() instanceof ASTAdd || this.getLeft() instanceof ASTMult || this.getLeft() instanceof ASTOpp) {
			ls.addAll(getLeft().code());
			left = ls.get(i);
			i++;
		} else {	  
			SimpleNode l = (SimpleNode)this.jjtGetChild(0);
			left = new OOTConstant<OOTTypeInt>(new OOTTypeInt(),String.valueOf(l.jjtGetValue())); 
		}

		opp= new OOTOper(left,null,"-");
		ls = new ArrayList<OOTStatement>();
		ls.add(opp);
		
		return ls;
	}
}
/* JavaCC - OriginalChecksum=f91ad1526c41afa8c81de02a1df44a6d (do not edit this line) */
