/* Generated By:JJTree: Do not edit this line. ASTRef.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRef extends SimpleNode {
  public ASTRef(int id) {
    super(id);
  }

  public ASTRef(Parser p, int id) {
    super(p, id);
  }
  
  public Type type() throws TypeException {
	  ASTType reftype=new ASTType(ParserTreeConstants.JJTTYPE);
	  reftype.jjtSetValue("Ref");
	  return reftype;
  }
  
  public boolean equals(Object o) {
	  if(o instanceof ASTRef)
		  return true;
	  return false;
  }

}
/* JavaCC - OriginalChecksum=2f315b4bd392311ea7d9d221f4396494 (do not edit this line) */
