/* Generated By:JJTree: Do not edit this line. ASTSeq.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTSeq extends SimpleNode {
  public ASTSeq(int id) {
    super(id);
  }

  public ASTSeq(Parser p, int id) {
    super(p, id);
  }
  
  public Type type() throws TypeException {
	  Node left = (Node)jjtGetChild(0);
	  ASTProc proctype = new ASTProc(ParserTreeConstants.JJTTYPE);

	  if(!left.type().equals(proctype.type()))
	  {

		  throw new TypeException("Left part type is not Proc");
	  }
	  Node right = (Node)jjtGetChild(this.jjtGetNumChildren()-1);
	  return  right.type();
  }
}
/* JavaCC - OriginalChecksum=3164b34b89f2b54d6c7a47399be0a226 (do not edit this line) */

