/* Generated By:JJTree: Do not edit this line. ASTTypeVar.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTypeVar extends SimpleNode implements Type {
  public ASTTypeVar(int id) {
    super(id);
  }

  public ASTTypeVar(Parser p, int id) {
    super(p, id);
  }

  /* MY CUSTOMIZATION OF ASTTypeVar */  
  
  public String getName() {return (String) jjtGetValue();}
  
  public String toString() {return super.toString()+" "+getName();}
	// override the way this node displays so as to give the variable name
  
  public boolean equals(Object obj){
	if (obj instanceof ASTTypeVar) {
		return ((ASTTypeVar) obj).getName().equals(getName());
	}
	else return false;
  }
  
  
  
}
/* JavaCC - OriginalChecksum=6920281831b636ac1ff345aef170abde (do not edit this line) */
