/* Generated By:JJTree: Do not edit this line. ASTType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTType extends SimpleNode implements Type {
  public ASTType(int id) {
    super(id);
  }

  public ASTType(Parser p, int id) {
    super(p, id);
  }

  
  /* MY CUSTOMIZATION OF ASTType */  
  
  public String getName() {return (String) jjtGetValue();}
  
  public String toString() {return super.toString()+" "+getName();}
	// override the way this node displays so as to give the type name
  
  public boolean equals(Object obj){
	if (obj instanceof ASTType) {
		return ((ASTType) obj).getName().equals(getName());
	}
	else return false;
  



  }
  
  
}
/* JavaCC - OriginalChecksum=7ebd00fea1859de09dd406ec0cdff226 (do not edit this line) */
