/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int fun = 6;
  /** RegularExpression Id. */
  int arrow = 7;
  /** RegularExpression Id. */
  int mapsto = 8;
  /** RegularExpression Id. */
  int mif = 9;
  /** RegularExpression Id. */
  int mthen = 10;
  /** RegularExpression Id. */
  int melse = 11;
  /** RegularExpression Id. */
  int let = 12;
  /** RegularExpression Id. */
  int in = 13;
  /** RegularExpression Id. */
  int mtrue = 14;
  /** RegularExpression Id. */
  int mfalse = 15;
  /** RegularExpression Id. */
  int and = 16;
  /** RegularExpression Id. */
  int or = 17;
  /** RegularExpression Id. */
  int eq = 18;
  /** RegularExpression Id. */
  int leq = 19;
  /** RegularExpression Id. */
  int geq = 20;
  /** RegularExpression Id. */
  int set = 21;
  /** RegularExpression Id. */
  int mnull = 22;
  /** RegularExpression Id. */
  int print = 23;
  /** RegularExpression Id. */
  int recv = 24;
  /** RegularExpression Id. */
  int from = 25;
  /** RegularExpression Id. */
  int send = 26;
  /** RegularExpression Id. */
  int to = 27;
  /** RegularExpression Id. */
  int at = 28;
  /** RegularExpression Id. */
  int mnew = 29;
  /** RegularExpression Id. */
  int TYPE = 30;
  /** RegularExpression Id. */
  int NUM = 31;
  /** RegularExpression Id. */
  int TERMVAR = 32;
  /** RegularExpression Id. */
  int TYPEVAR = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"fun\"",
    "\"->\"",
    "\"|->\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"let\"",
    "\"in\"",
    "\"true\"",
    "\"false\"",
    "\"and\"",
    "\"or\"",
    "\"==\"",
    "<leq>",
    "<geq>",
    "\"=\"",
    "\"O\"",
    "\"print_int\"",
    "\"recv\"",
    "\"from\"",
    "\"send\"",
    "\"to\"",
    "\"at\"",
    "\"new\"",
    "<TYPE>",
    "<NUM>",
    "<TERMVAR>",
    "<TYPEVAR>",
    "\".\"",
    "\"!\"",
    "\"-\"",
    "\"#\"",
    "\"(\"",
    "\")\"",
    "\"~\"",
    "\"<\"",
    "\">\"",
    "\"+\"",
    "\"*\"",
    "\";\"",
    "\",\"",
  };

}
