/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTBOOL = 2;
  public int JJTNOT = 3;
  public int JJTINT = 4;
  public int JJTOPP = 5;
  public int JJTREF = 6;
  public int JJTNULL = 7;
  public int JJTPRINT = 8;
  public int JJTAND = 9;
  public int JJTOR = 10;
  public int JJTIDY = 11;
  public int JJTEQ = 12;
  public int JJTLEQ = 13;
  public int JJTGEQ = 14;
  public int JJTLT = 15;
  public int JJTGT = 16;
  public int JJTADD = 17;
  public int JJTMULT = 18;
  public int JJTSEQ = 19;
  public int JJTAPP = 20;
  public int JJTTERMVAR = 21;
  public int JJTFUN = 22;
  public int JJTLET = 23;
  public int JJTIF = 24;
  public int JJTRECV = 25;
  public int JJTSEND = 26;
  public int JJTNEW = 27;
  public int JJTARROWTYPE = 28;
  public int JJTTYPE = 29;
  public int JJTTYPEVAR = 30;
  public int JJTProc = 31;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Bool",
    "Not",
    "Int",
    "Opp",
    "Ref",
    "Null",
    "Print",
    "And",
    "Or",
    "Idy",
    "Eq",
    "Leq",
    "Geq",
    "Lt",
    "Gt",
    "Add",
    "Mult",
    "Seq",
    "App",
    "TermVar",
    "Fun",
    "Let",
    "If",
    "Recv",
    "Send",
    "New",
    "ArrowType",
    "Type",
    "TypeVar",
    "Proc",
  };
}
/* JavaCC - OriginalChecksum=75e94482ff94980af2a3ecc64408ca07 (do not edit this line) */
